services:
  mongodb:
    image: mongo:7.0
    container_name: restaurant-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: restaurant_db
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - restaurant-network


  redis:
    image: redis:7.2-alpine
    container_name: restaurant-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes --requirepass redispassword
    volumes:
      - redis_data:/data
    networks:
      - restaurant-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: restaurant-redis-commander
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      REDIS_HOSTS: local:redis:6379:0:redispassword
    networks:
      - restaurant-network
    depends_on:
      - redis

volumes:
  mongodb_data:
  redis_data:

networks:
  restaurant-network:
    driver: bridge